package ru.sua.ssrrpats.service;

import org.springframework.stereotype.Service;
import ru.sua.ssrrpats.domain.HistoryRecord;
import ru.sua.ssrrpats.domain.ParsingResult;

import java.util.Date;

@Service
public class HistoryRecordFabImpl implements HistoryRecordFab {
    @Override
    public HistoryRecord convert(ParsingResult parsingResult) {
        HistoryRecord hr = new HistoryRecord();
        hr.setTimestamp(new java.sql.Timestamp(new Date().getTime()));
        hr.setTotalWords(parsingResult.totalWordsCount());
        hr.setUniqWords(parsingResult.uniqWordsCount());
        hr.setUrl(parsingResult.getRequestUrl());
        hr.setFullTextDelimeted(parsingResult.getFullTextDelimeted("|"));
        // hr.setId(); autogenerated
        return hr;
    }
}
